package(default_visibility = ["//visibility:public"])

cc_library(
  name = "call",
  hdrs = [
    "call.h",
    "internal/call.h"
  ],
  deps = [
    "//best/base:port",
    "//best/meta:init",
  ],
)