package(default_visibility = ["//visibility:public"])

cc_library(
  name = "fwd",
  hdrs = ["fwd.h"],
)

cc_library(
  name = "port",
  hdrs = ["port.h"],
)

cc_library(
  name = "unsafe",
  hdrs = ["unsafe.h"],
  deps = [":port"],
)