package(default_visibility = ["//visibility:public"])

cc_library(
  name = "app",
  hdrs = ["app.h"],
  srcs = ["app.cc"],
  deps = [
    "//best/log:wtf",
    "//best/text:strbuf",
    "//best/text:format",
  ]
)