package(default_visibility = ["//best:__subpackages__"])

cc_library(
  name = "crash",
  hdrs = ["crash.h"],
  srcs = ["crash.cc"],
  deps = [
    "//best/base:port",
    "//best/log:location",
  ],
)